- name: Install server and configure it
  hosts: all
  become: true
  roles:
    - role: fail2ban

    - role: geerlingguy.ntp
      vars:
        ntp_enabled: true
        ntp_timezone: Europe/Zurich
        ntp_area: 'ch'

    - role: geerlingguy.firewall
      vars:
        firewall_allowed_tcp_ports:
          - '22' # SSH
          - '9100' # node_exporter

    - role: deploy_ic_it_ssh_keys

    - role: geerlingguy.node_exporter
      vars:
        node_exporter_host: '0.0.0.0'
        node_exporter_port: 9100
  tasks:
    - name: Install NFS client
      ansible.builtin.apt:
        name: nfs-common
        state: present
      become: true

    - name: Mount the NFS volume
      ansible.posix.mount:
        path: /mnt/parsadata1
        src: ic1files.epfl.ch:u11837_ic_parsa_001_files_nfs
        fstype: nfs
        state: mounted
      become: true
